modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="bioinformatics" #mandatory

version="1.16.4-0.1" #mandatory

displayName="Bioinformatics" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="bioinformatics.png" #optional

credits="Thanks for TechnoVision made the video about minecraft modding" #optional

authors="lzlniu" #optional

description='''
The first mod made by lzlniu, about bioinformatics.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bioinformatics]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bioinformatics]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
